### PR TITLE
Using Vazir font for shops in RTL language

### PR DESCRIPTION
**Pull request by mparvazi**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | [Vazir](https://github.com/rastikerdar/vazir-font) is a Persian/Arabic font.
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| How to test?      | -
| Possible impacts? | Font face in RTL version of theme-refacto.

Screenshot 2022-01-21 at 11-52-07 Hummingbird printed t-shirt

Screenshot from 2022-01-21 11-54-51

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
Cool 👍

**Comment by NeOMakinG** [comment]
Thanks @mparvazi

**Comment by NeOMakinG** [comment]
Wait, I missed something, RTL is not about only arabic font right?

This is managed by the PS core isn't it?

**Comment by mparvazi** [comment]
RTL scripts:

- Arabic script (Arabic / Persian / Urdu / Punjabi / Malay)
- Hebrew alphabet

Vazir font is based on [DejaVu Sans 2.35](https://dejavu-fonts.github.io/) and extended for Arabic scripts.
If the RTL language doesn't use Arabic script, then "DejaVu Sans" will be used.

**Pull request merged**
