### PR TITLE
Add to cart Spinner

### PR DESCRIPTION
**Pull request by mparvazi**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Adds a spinner to add-to-cart button after clicking by user.
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| How to test?      | -
| Possible impacts? | Add to cart button.

### CODE REVIEW

**Comment by prestarocket** [comment]
@mparvazi What's happen on prestashop handleError ? 

prestashop.on('handleError', function (event) { etc..

@mparvazi could you contact me (prestarocket@gmail.com), i have something to ask you in private)

**Comment by mparvazi** [comment]
Hello @prestarocket 

Thanks for your suggestion.

PR will be checked by @NeOMakinG and he wont approve PR easily.
I just wanted to show this feature can be add to the theme-refacto.

**Comment by SharakPL** [comment]
Will the theme still use jquery? I'd recommend to stick with js/ts.

**Comment by NeOMakinG** [comment]
> Will the theme still use jquery? I'd recommend to stick with js/ts.

No it shouldn't use jQuery

**Comment by mparvazi** [comment]
Code should be changed?

**Pull request closed without merging**
