### PR TITLE
Bs4 classes qv carousel

### PR DESCRIPTION
**Pull request by rodriciru**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Replaces old BS4 classes by BS5 new classes; Modal changes, Qickview updated, Slider in qv
| Type?             | improvement
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/theme-refacto/issues/115.
| How to test?      | Installa theme and check a product whit multiple images.
| Possible impacts? | None, at least i know.

### CODE REVIEW

**Comment by SharakPL** [comment]
Nice job, but honestly I would get rid of all the floats, expecially from links and buttons with icons. It can be done much better with flex.

**Comment by NeOMakinG** [comment]
@rodriciru can you rebase? You've some conflict

**Comment by NeOMakinG** [comment]
@Hlavtox wdyt?

**Comment by NeOMakinG** [comment]
> Nice job, but honestly I would get rid of all the floats, especially from links and buttons with icons. It can be done much better with flex.

I can't agree more :)

**Comment by Hlavtox** [comment]
@SharakPL Pls do not use merge commit, rebase the PR instead

**Comment by Hlavtox** [comment]
Otherwise, looks good, merge it when ready ;-)

**Comment by rodriciru** [comment]
Im mega new to git, so i dont know how to do many thing. I try my best, and i think i do it correctly, but i dont know!

**Comment by NeOMakinG** [comment]
I did it for you @rodriciru 

`git rebase develop` and fixed conflict, then `git push rodriciru/BS4Classes-Qv-Carousel -f`

**Review by NeOMakinG — APPROVED** [review]

**Comment by NeOMakinG** [comment]
Keep in mind that we need to get rid of all these floats

**Comment by Hlavtox** [comment]
@NeOMakinG Already in the list - https://github.com/PrestaShop/theme-refacto/issues/117

**Comment by rodriciru** [comment]
thank you all!!!
Im working on stylelint fixes, so maybe i will do a new PR, hopefully this time wil be ok!

**Pull request merged**
